# Generated by Django 4.2.5 on 2023-11-01 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interrogazioni', '0002_remove_materia_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='url_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lastinterrogation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
