# Generated by Django 4.2.5 on 2023-12-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interrogazioni', '0004_lastinterrogation_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastInterrogation',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
