# Generated by Django 5.2.6 on 2025-09-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interrogazioni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('studenti_estraibili', models.ManyToManyField(related_name='estrazioni_possibili', to='interrogazioni.studente')),
                ('studenti_estratti', models.ManyToManyField(blank=True, related_name='estrazioni_effettive', to='interrogazioni.studente')),
            ],
        ),
    ]
