# Generated by Django 5.2.6 on 2025-10-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrazioni', '0002_estrazione_titolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estrazione',
            name='studenti_estratti',
        ),
        migrations.AddField(
            model_name='estrazione',
            name='ordine_estratti',
            field=models.TextField(blank=True, null=True),
        ),
    ]
