# Generated by Django 5.2.6 on 2025-10-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrazioni', '0003_remove_estrazione_studenti_estratti_and_more'),
        ('interrogazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrazione',
            name='studenti_estratti',
            field=models.ManyToManyField(blank=True, related_name='estrazioni_effettive', to='interrogazioni.studente'),
        ),
    ]
