# Generated by Django 5.2.6 on 2025-11-06 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interrogazioni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterrogazioneProgrammata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('note', models.TextField(blank=True, help_text='Optional notes about this scheduled interrogation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogazioni_programmate', to='interrogazioni.materia')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogazioni_programmate', to='interrogazioni.studente')),
            ],
            options={
                'verbose_name': 'Interrogazione Programmata',
                'verbose_name_plural': 'Interrogazioni Programmate',
                'ordering': ['data', 'materia', 'studente'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_endpoint', models.URLField(max_length=500)),
                ('subscription_p256dh', models.CharField(max_length=200)),
                ('subscription_auth', models.CharField(max_length=200)),
                ('notified_one_week', models.BooleanField(default=False)),
                ('notified_two_days', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='calendario.interrogazioneprogrammata')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to='interrogazioni.studente')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'unique_together': {('studente', 'evento')},
            },
        ),
    ]
