# Generated by Django 5.2.6 on 2025-11-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSubscription',
        ),
    ]
