# Generated by Django 5.2.6 on 2025-09-28 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interrogazioni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('contenuto', models.TextField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appunti', to='interrogazioni.materia')),
            ],
        ),
    ]
