# Generated by Django 5.2.6 on 2025-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appunti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appunto',
            name='titolo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
