# Generated by Django 5.2.6 on 2025-10-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageoftheday',
            old_name='message',
            new_name='text',
        ),
    ]
